name: "Deploy Dev"

inputs:
  GITHUB_TOKEN:
    required: true
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY: 
    required: true

runs:
  using: "composite"
  steps:
  
    - name: Terraform Init
        run: terraform init
        working-directory: '.github/terraform'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    - name: Terraform Apply   
      shell: bash
      run: terraform apply -auto-approve
      working-directory: '.github/terraform'
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID:  ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ inputs.AWS_SECRET_ACCESS_KEY }}
