name: Prod Release

on:
  push:
    branches: [ "demo-app-flow" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  dev:
    uses: ./.github/workflows/demo-ghflow.yml
    secrets:
      #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      MYENV: 'CI'
      
